'use strict';
const STATUSES=['Neu','Kontakt aufgenommen','Termin vereinbart','Nachfassen','Bestellung','Abgeschlossen'];
const INTERESTS=['Produkte','Brush & Learn','iTOP','Hydrosonic','Interdentalbürsten','Mundpflege'];
const STORAGE_KEY='praxisbesuchs-planer-v2';
const $=id=>document.getElementById(id);
const els={list:$('practiceList'),followups:$('followupList'),dialog:$('practiceDialog'),form:$('practiceForm')};
let practices=loadPractices();
function uuid(){return crypto.randomUUID?crypto.randomUUID():`${Date.now()}-${Math.random()}`;}
function seedData(){return [];}
function loadPractices(){try{const raw=localStorage.getItem(STORAGE_KEY);return raw?JSON.parse(raw):seedData();}catch{return seedData();}}
function save(){localStorage.setItem(STORAGE_KEY,JSON.stringify(practices));}
function formatDate(v){if(!v)return '—';return new Intl.DateTimeFormat('de-DE').format(new Date(v+'T12:00:00'));}
function todayISO(){return new Date().toISOString().slice(0,10);}
function isOpen(p){return p.followUpDate&&p.status!=='Abgeschlossen';}
function normalize(v){return String(v??'').trim();}
function showNotice(text,type='success'){const n=$('importNotice');n.hidden=false;n.className=`notice ${type}`;n.textContent=text;setTimeout(()=>n.hidden=true,9000);}
function initializeOptions(){STATUSES.forEach(s=>[$('statusFilter'),$('status')].forEach(sel=>{const o=document.createElement('option');o.value=s;o.textContent=s;sel.append(o);}));INTERESTS.forEach(i=>{const l=document.createElement('label');l.innerHTML=`<input type="checkbox" value="${i}"> ${i}`;$('interestOptions').append(l);});$('todayLabel').textContent=new Intl.DateTimeFormat('de-DE',{weekday:'long',day:'2-digit',month:'long'}).format(new Date());}
function render(){renderStats();renderFollowups();renderPractices();}
function renderStats(){$('statAll').textContent=practices.length;$('statOpen').textContent=practices.filter(isOpen).length;$('statAppointments').textContent=practices.filter(p=>p.status==='Termin vereinbart').length;$('statOrders').textContent=practices.filter(p=>p.status==='Bestellung').length;}
function renderFollowups(){els.followups.innerHTML='';const open=practices.filter(isOpen).sort((a,b)=>a.followUpDate.localeCompare(b.followUpDate)).slice(0,6);if(!open.length){els.followups.innerHTML='<p class="empty-state">Aktuell sind keine Wiedervorlagen offen.</p>';return;}open.forEach(p=>{const item=document.createElement('article');item.className='followup-item'+(p.followUpDate<todayISO()?' overdue':'');item.innerHTML=`<p>${escapeHtml(p.city)} · ${escapeHtml(p.status)}</p><strong>${escapeHtml(p.name)}</strong><span>${formatDate(p.followUpDate)}</span>`;item.onclick=()=>openDialog(p.id);els.followups.append(item);});}
function filteredPractices(){const q=$('searchInput').value.trim().toLowerCase(),status=$('statusFilter').value,city=$('cityFilter').value.trim().toLowerCase(),date=$('dateFilter').value;return practices.filter(p=>(!q||[p.name,p.customerNumber,p.address,p.city,p.contactPerson,p.phone,p.email].some(v=>(v||'').toLowerCase().includes(q)))&&(!status||p.status===status)&&(!city||(p.city||'').toLowerCase().includes(city))&&(!date||p.followUpDate===date));}
function mapsUrl(p){return `https://www.google.com/maps/search/?api=1&query=${encodeURIComponent([p.name,p.address].filter(Boolean).join(', '))}`;}
function searchUrl(p){return `https://www.google.com/search?q=${encodeURIComponent([p.name,p.city,'Zahnarzt Apotheke'].filter(Boolean).join(' '))}`;}
function renderPractices(){els.list.innerHTML='';const data=filteredPractices();$('resultCount').textContent=`${data.length.toLocaleString('de-DE')} von ${practices.length.toLocaleString('de-DE')} Kunden`;$('emptyState').hidden=data.length>0;data.sort((a,b)=>a.name.localeCompare(b.name,'de')).slice(0,500).forEach(p=>{const node=$('practiceCardTemplate').content.cloneNode(true);const badge=node.querySelector('.status-badge');badge.textContent=p.status;badge.dataset.status=p.status;node.querySelector('.practice-title').textContent=p.name;node.querySelector('.customer-number').textContent=p.customerNumber?`Kundennummer ${p.customerNumber}`:'Keine Kundennummer';node.querySelector('.practice-address').textContent=p.address;node.querySelector('.map-btn').href=mapsUrl(p);node.querySelector('.search-btn').href=searchUrl(p);const contact=node.querySelector('.contact-row');contact.innerHTML=[p.contactPerson&&`<span>👤 ${escapeHtml(p.contactPerson)}</span>`,p.phone&&`<a href="tel:${encodeURIComponent(p.phone)}">☎ ${escapeHtml(p.phone)}</a>`,p.email&&`<a href="mailto:${encodeURIComponent(p.email)}">✉ E-Mail</a>`,p.website&&`<a href="${escapeHtml(p.website)}" target="_blank" rel="noopener">🌐 Website</a>`].filter(Boolean).join('');const tags=node.querySelector('.tag-list');(p.interests||[]).forEach(i=>{const s=document.createElement('span');s.textContent=i;tags.append(s);});node.querySelector('.last-visit').textContent=`Letzter Besuch: ${formatDate(p.lastVisit)}`;node.querySelector('.follow-up').textContent=`Wiedervorlage: ${formatDate(p.followUpDate)}`;node.querySelector('.notes-preview').textContent=p.notes||'Keine Gesprächsnotizen.';node.querySelector('.edit-btn').onclick=()=>openDialog(p.id);els.list.append(node);});if(data.length>500)$('resultCount').textContent+=` · Aus Leistungsgründen werden die ersten 500 angezeigt`;}
function escapeHtml(v=''){return String(v).replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));}
function openDialog(id){els.form.reset();$('practiceId').value='';$('deleteBtn').hidden=true;$('dialogTitle').textContent='Praxis anlegen';if(id){const p=practices.find(x=>x.id===id);if(!p)return;$('dialogTitle').textContent='Kunde bearbeiten';$('deleteBtn').hidden=false;Object.entries({practiceId:p.id,practiceName:p.name,customerNumber:p.customerNumber,address:p.address,city:p.city,phone:p.phone,email:p.email,website:p.website,contactPerson:p.contactPerson,status:p.status,lastVisit:p.lastVisit,followUpDate:p.followUpDate,notes:p.notes}).forEach(([k,v])=>$(k).value=v||'');document.querySelectorAll('#interestOptions input').forEach(cb=>cb.checked=(p.interests||[]).includes(cb.value));}else $('status').value='Neu';els.dialog.showModal();}
function closeDialog(){els.dialog.close();}
function formData(){return{id:$('practiceId').value||uuid(),name:$('practiceName').value.trim(),customerNumber:$('customerNumber').value.trim(),address:$('address').value.trim(),city:$('city').value.trim(),phone:$('phone').value.trim(),email:$('email').value.trim(),website:$('website').value.trim(),contactPerson:$('contactPerson').value.trim(),status:$('status').value,lastVisit:$('lastVisit').value,followUpDate:$('followUpDate').value,notes:$('notes').value.trim(),interests:[...document.querySelectorAll('#interestOptions input:checked')].map(x=>x.value)};}
function rowToPractice(row){const name=normalize(row.Firma||row.Firma1||row.Praxisname||row.Name);const street=[row.Straße||row.Strasse,row.Hausnummer].map(normalize).filter(Boolean).join(' ');const city=normalize(row.Ort);const address=[street,[normalize(row.PLZ),city].filter(Boolean).join(' ')].filter(Boolean).join(', ');const contact=[row.Titel,row.Vorname,row.Name].map(normalize).filter(Boolean).join(' ');return{id:uuid(),name,customerNumber:normalize(row.Kundennummer),address,city,phone:normalize(row.Telefon),email:normalize(row['E-Mail']||row.Email),website:normalize(row.Website),contactPerson:contact,status:'Neu',lastVisit:'',followUpDate:'',notes:'',interests:[],source:'Excel'};}
function dedupeKey(p){return p.customerNumber?`kn:${p.customerNumber}`:`adr:${(p.name+'|'+p.address).toLowerCase().replace(/\s+/g,' ')}`;}
async function importExcel(file){if(!window.XLSX){showNotice('Excel-Bibliothek konnte nicht geladen werden. Bitte Internetverbindung prüfen.','error');return;}try{const data=await file.arrayBuffer();const wb=XLSX.read(data,{type:'array',cellDates:true});const ws=wb.Sheets[wb.SheetNames[0]];const rows=XLSX.utils.sheet_to_json(ws,{defval:''});const imported=rows.map(rowToPractice).filter(p=>p.name);const existing=new Set(practices.map(dedupeKey));let added=0,skipped=0;for(const p of imported){const key=dedupeKey(p);if(existing.has(key)){skipped++;continue;}practices.push(p);existing.add(key);added++;}save();render();showNotice(`${added.toLocaleString('de-DE')} Kunden importiert, ${skipped.toLocaleString('de-DE')} mögliche Dubletten übersprungen.`);}catch(err){console.error(err);showNotice('Die Excel-Datei konnte nicht gelesen werden. Bitte prüfe das Dateiformat.','error');}}
function exportBackup(){const payload=JSON.stringify({exportedAt:new Date().toISOString(),practices},null,2);const blob=new Blob([payload],{type:'application/json'});const a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download=`praxisbesuchs-planer-sicherung-${todayISO()}.json`;a.click();URL.revokeObjectURL(a.href);}
els.form.addEventListener('submit',e=>{e.preventDefault();if(!els.form.reportValidity())return;const p=formData(),i=practices.findIndex(x=>x.id===p.id);if(i>=0)practices[i]=p;else practices.push(p);save();closeDialog();render();});
$('deleteBtn').onclick=()=>{const id=$('practiceId').value;if(id&&confirm('Diesen Kunden wirklich löschen?')){practices=practices.filter(p=>p.id!==id);save();closeDialog();render();}};
$('newPracticeBtn').onclick=()=>openDialog();$('closeDialogBtn').onclick=closeDialog;$('cancelBtn').onclick=closeDialog;
['searchInput','statusFilter','cityFilter','dateFilter'].forEach(id=>$(id).addEventListener('input',renderPractices));
$('resetFiltersBtn').onclick=()=>{['searchInput','statusFilter','cityFilter','dateFilter'].forEach(id=>$(id).value='');renderPractices();};
$('excelInput').addEventListener('change',e=>{const f=e.target.files[0];if(f)importExcel(f);e.target.value='';});
$('exportBtn').onclick=exportBackup;$('clearBtn').onclick=()=>{if(confirm('Alle lokal gespeicherten Kundendaten löschen? Diese Aktion kann nicht rückgängig gemacht werden.')){practices=[];save();render();showNotice('Lokale Daten wurden gelöscht.');}};
els.dialog.addEventListener('click',e=>{if(e.target===els.dialog)closeDialog();});
if('serviceWorker' in navigator)window.addEventListener('load',()=>navigator.serviceWorker.register('./service-worker.js').catch(console.error));
initializeOptions();render();
